// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniItHelpdesk.Data;

#nullable disable

namespace MiniItHelpdesk.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831094814_SeedMoreData")]
    partial class SeedMoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("MiniItHelpdesk.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Checked the printer, seems to be a driver issue. Reinstalling now.",
                            TicketId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 11, 11, 45, 0, 0, DateTimeKind.Utc),
                            Text = "Reset the password, please try logging in again.",
                            TicketId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 11, 12, 30, 0, 0, DateTimeKind.Utc),
                            Text = "Still getting the same error after the reset.",
                            TicketId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 8, 9, 15, 0, 0, DateTimeKind.Utc),
                            Text = "ISP confirmed an outage in the area, resolved now.",
                            TicketId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Text = "License purchased and installed.",
                            TicketId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 1, 12, 9, 30, 0, 0, DateTimeKind.Utc),
                            Text = "Tried a different cable, issue persists.",
                            TicketId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 1, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Investigating VPN server logs for drop causes.",
                            TicketId = 6,
                            UserId = 5
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 1, 13, 14, 10, 0, 0, DateTimeKind.Utc),
                            Text = "Happens more often in the afternoon, for what it's worth.",
                            TicketId = 6,
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 1, 14, 13, 20, 0, 0, DateTimeKind.Utc),
                            Text = "Account unlocked, please try again.",
                            TicketId = 7,
                            UserId = 6
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Approval pending from IT budget owner.",
                            TicketId = 8,
                            UserId = 6
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 1, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Reconfigured mobile mail settings, sync restored.",
                            TicketId = 9,
                            UserId = 5
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 1, 16, 16, 45, 0, 0, DateTimeKind.Utc),
                            Text = "Confirmed working on my phone now, thanks!",
                            TicketId = 9,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("MiniItHelpdesk.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Hardware",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 30, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "The printer on the second floor is unresponsive, likely a driver issue.",
                            Priority = "Medium",
                            Status = "Open",
                            Title = "Printer not working"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToUserId = 2,
                            Category = "Software",
                            CreatedAt = new DateTime(2025, 1, 11, 11, 15, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Login returns 'Invalid credentials' error even though the password is correct.",
                            Priority = "High",
                            Status = "InProgress",
                            Title = "Cannot log into the system"
                        },
                        new
                        {
                            Id = 3,
                            AssignedToUserId = 2,
                            Category = "Network",
                            CreatedAt = new DateTime(2025, 1, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            Description = "Internet has been extremely slow since this morning, affecting the whole team.",
                            Priority = "Low",
                            Status = "Resolved",
                            Title = "Slow internet connection"
                        },
                        new
                        {
                            Id = 4,
                            AssignedToUserId = 2,
                            Category = "Software",
                            CreatedAt = new DateTime(2025, 1, 5, 14, 45, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Adobe Photoshop license needed for a new employee.",
                            Status = "Closed",
                            Title = "New software license needed"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Hardware",
                            CreatedAt = new DateTime(2025, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 3,
                            Description = "External monitor flickers randomly, possibly a cable or driver issue.",
                            Priority = "Low",
                            Status = "Open",
                            Title = "Monitor flickering"
                        },
                        new
                        {
                            Id = 6,
                            AssignedToUserId = 5,
                            Category = "Network",
                            CreatedAt = new DateTime(2025, 1, 13, 10, 20, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 4,
                            Description = "VPN disconnects every few minutes when working from home.",
                            Priority = "High",
                            Status = "InProgress",
                            Title = "VPN connection drops"
                        },
                        new
                        {
                            Id = 7,
                            AssignedToUserId = 6,
                            Category = "Account",
                            CreatedAt = new DateTime(2025, 1, 14, 13, 5, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 7,
                            Description = "Account got locked after several failed login attempts, needs unlocking.",
                            Priority = "Medium",
                            Status = "Resolved",
                            Title = "Account locked out"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Hardware",
                            CreatedAt = new DateTime(2025, 1, 15, 8, 45, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 3,
                            Description = "Current laptop is too slow for daily tasks, requesting a replacement.",
                            Priority = "Medium",
                            Status = "Open",
                            Title = "New laptop request"
                        },
                        new
                        {
                            Id = 9,
                            AssignedToUserId = 5,
                            Category = "Software",
                            CreatedAt = new DateTime(2025, 1, 16, 15, 30, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 4,
                            Description = "Emails are not syncing on mobile device, only on desktop.",
                            Priority = "Low",
                            Status = "Closed",
                            Title = "Email sync issues"
                        });
                });

            modelBuilder.Entity("MiniItHelpdesk.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "employee@test.com",
                            Name = "Employee",
                            PasswordHash = "$2a$11$LaHBE4wxxt2gjQUIVdnODu.Q6XfErT/61N/G/hW.RqV.RuoskmGS.",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 2,
                            Email = "direct.manager@test.com",
                            Name = "Direct Manager",
                            PasswordHash = "$2a$11$LaHBE4wxxt2gjQUIVdnODu.Q6XfErT/61N/G/hW.RqV.RuoskmGS.",
                            Role = "ITAgent"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ana.petrovic@test.com",
                            Name = "Ana Petrović",
                            PasswordHash = "$2a$11$LaHBE4wxxt2gjQUIVdnODu.Q6XfErT/61N/G/hW.RqV.RuoskmGS.",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 4,
                            Email = "marko.jovanovic@test.com",
                            Name = "Marko Jovanović",
                            PasswordHash = "$2a$11$LaHBE4wxxt2gjQUIVdnODu.Q6XfErT/61N/G/hW.RqV.RuoskmGS.",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 5,
                            Email = "jelena.nikolic@test.com",
                            Name = "Jelena Nikolić",
                            PasswordHash = "$2a$11$LaHBE4wxxt2gjQUIVdnODu.Q6XfErT/61N/G/hW.RqV.RuoskmGS.",
                            Role = "ITAgent"
                        },
                        new
                        {
                            Id = 6,
                            Email = "stefan.ilic@test.com",
                            Name = "Stefan Ilić",
                            PasswordHash = "$2a$11$LaHBE4wxxt2gjQUIVdnODu.Q6XfErT/61N/G/hW.RqV.RuoskmGS.",
                            Role = "ITAgent"
                        },
                        new
                        {
                            Id = 7,
                            Email = "milica.stankovic@test.com",
                            Name = "Milica Stanković",
                            PasswordHash = "$2a$11$LaHBE4wxxt2gjQUIVdnODu.Q6XfErT/61N/G/hW.RqV.RuoskmGS.",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 8,
                            Email = "admin@test.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$LaHBE4wxxt2gjQUIVdnODu.Q6XfErT/61N/G/hW.RqV.RuoskmGS.",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("MiniItHelpdesk.Models.Comment", b =>
                {
                    b.HasOne("MiniItHelpdesk.Models.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniItHelpdesk.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniItHelpdesk.Models.Ticket", b =>
                {
                    b.HasOne("MiniItHelpdesk.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MiniItHelpdesk.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
