// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniItHelpdesk.Data;

#nullable disable

namespace MiniItHelpdesk.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("MiniItHelpdesk.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MiniItHelpdesk.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Hardware",
                            CreatedAt = new DateTime(2025, 1, 10, 9, 30, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "The printer on the second floor is unresponsive, likely a driver issue.",
                            Priority = "Medium",
                            Status = "Open",
                            Title = "Printer not working"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToUserId = 2,
                            Category = "Software",
                            CreatedAt = new DateTime(2025, 1, 11, 11, 15, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Login returns 'Invalid credentials' error even though the password is correct.",
                            Priority = "High",
                            Status = "InProgress",
                            Title = "Cannot log into the system"
                        },
                        new
                        {
                            Id = 3,
                            AssignedToUserId = 2,
                            Category = "Network",
                            CreatedAt = new DateTime(2025, 1, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            Description = "Internet has been extremely slow since this morning, affecting the whole team.",
                            Priority = "Low",
                            Status = "Resolved",
                            Title = "Slow internet connection"
                        },
                        new
                        {
                            Id = 4,
                            AssignedToUserId = 2,
                            Category = "Software",
                            CreatedAt = new DateTime(2025, 1, 5, 14, 45, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Adobe Photoshop license needed for a new employee.",
                            Status = "Closed",
                            Title = "New software license needed"
                        });
                });

            modelBuilder.Entity("MiniItHelpdesk.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "employee@test.com",
                            Name = "Employee",
                            Role = "Employee"
                        },
                        new
                        {
                            Id = 2,
                            Email = "direct.manager@test.com",
                            Name = "Direct Manager",
                            Role = "ITAgent"
                        });
                });

            modelBuilder.Entity("MiniItHelpdesk.Models.Comment", b =>
                {
                    b.HasOne("MiniItHelpdesk.Models.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniItHelpdesk.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniItHelpdesk.Models.Ticket", b =>
                {
                    b.HasOne("MiniItHelpdesk.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MiniItHelpdesk.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
